apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nothing-api-default-deny
  namespace: nothing
spec:
  podSelector:
    matchLabels:
      app: nothing-api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: 8080
  egress:
    - ports:
        - protocol: TCP
          port: 5432
    - ports:
        - protocol: TCP
          port: 443
    - ports:
        - protocol: UDP
          port: 53
      to: []


---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nothing-payment-egress
  namespace: nothing
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - nothing-xrpl-worker
          - nothing-billing-maintenance
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress:
    - ports:
        - protocol: TCP
          port: 5432
    - ports:
        - protocol: TCP
          port: 443
    - ports:
        - protocol: UDP
          port: 53
